### ISSUE TITLE
panic when adding invalid RR value

### ISSUE THREAD

**Issue by jrwren** [jrwren/domasimu#15]
```
$ ~/bin/domasimu -u 'xmtp.net test1 A - 2899904718 300'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x642d92]

goroutine 1 [running]:
main.createOrUpdate(0xc000096960, 0x7ffcc338e6b1, 0x21, 0xc00024a353, 0x3, 0x0, 0x444fe6, 0xc0000841cd, 0x6d6f97)
        /home/jrwren/go/src/github.com/jrwren/domasimu/cmd/domasimu/main.go:279 +0x272
main.main()
        /home/jrwren/go/src/github.com/jrwren/domasimu/cmd/domasimu/main.go:97 +0x7c1
```

expect: this to not panic.

**Comment by jrwren** [comment]
fixed in 2f7175b52f24123328c2aa1c9eb453ae72053d52
